### ISSUE TITLE
服务启动失败

### ISSUE THREAD

**Issue by DataGods** [BuGuangshuo/MoneyManageSystem#1]
我尝试输入yarn run start但是服务保存显示启动失败

![image](https://github.com/BuGuangshuo/MoneyManageSystem/assets/144096219/06037291-492c-4cd3-9402-e3ae4b057077)

**Comment by BuGuangshuo** [comment]
vite框架默认启动命令是yarn run dev 或你直接使用yarn start也能直接启动

**Comment by DataGods** [comment]
好的 刚试了yarn run dev成功启动了 感谢
